import React, {useState, useContext, useRef} from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { FaFacebook, FaLinkedinIn, FaGoogle, FaRegEnvelope, FaUserAlt } from 'react-icons/fa'
import { MdLockOutline } from 'react-icons/md'
import { useRouter } from 'next/router'
import {useAppContext} from '../stores/appContext'

const Login = () => {
    const { user, login} = useAppContext();
    const router = useRouter()
    
    const usernameRef = useRef('admin');
    const passwordRef = useRef('123');

    const handleClick = (e) =>{
        e.preventDefault();
        const username = usernameRef.current.value;
        const password = passwordRef.current.value;
     
        login(username, password)
    }

  

  return (
    <div className="flex flex-col items-center justify-center  py-2 bg-gary-100">
      <Head>
        <title>POWERLINE</title>
        <meta name="description" content="Generated by eli" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className='bg-white dark:bg-[#191919] rounded-2xl shadow-2xl flex w-2/3 max-w-4xl'>
          <div className={`w-3/5 p-5 relative ${user && "blur-[2px]"}`} >
            <div className={`w-full h-full absolute inset-0  z-50 rounded-2xl rounded-r-none ${user ? " block " : " hidden "}`}></div>
            <div className='text-left font-bold '><span className='text-red-500'>PowerLine</span></div>
            <div className='py-10'>
              <h3 className='text-3xl font-bold text-red-500 mb-2'>Sing in to Account</h3>
              <div className='border-2 w-10 border-red-500 inline-block mb-2'></div>
              <div className='flex justify-center my-2'>
                <a href='#' className='border-2 border-gray-200 dark:border-gray-500 rounded-full p-3 mx-1'>
                  <FaFacebook className='text-sm text-gray-500 dark:text-gray-400'/>
                </a> 
                <a href='#' className='border-2 border-gray-200 dark:border-gray-500 rounded-full p-3 mx-1'>
                  <FaLinkedinIn className='text-sm text-gray-500 dark:text-gray-400'/>
                </a> 
                <a href='#' className='border-2 border-gray-200 dark:border-gray-500 rounded-full p-3 mx-1'>
                  <FaGoogle className='text-sm text-gray-500 dark:text-gray-400 '/>
                </a> 
              </div>{/* Social login section */}
              <p className='text-gray-400 py-2'>Please use your email account</p>
              <div className='flex flex-col items-center'>
                <div className='bg-gray-100 dark:bg-gray-300 w-64 p-2 flex items-center mb-3'>
                  <FaUserAlt className='text-gray-400 dark:text-gray-500  m-2'/>
                  <input type='text' placeholder='Username' name="username" ref={usernameRef} className='bg-gray-100 dark:bg-gray-300 outline-none text-sm  flex-1'/>
                </div>
                <br />
                <div className='bg-gray-100 dark:bg-gray-300 w-64 p-2 flex items-center mb-3'>
                  <MdLockOutline className='text-gray-400 dark:text-gray-500 m-2'/>
                  <input type="password" placeholder='Password' name="password" ref={passwordRef} className='bg-gray-100 dark:bg-gray-300 outline-none text-sm flex-1'/>
                </div>
                <div className='flex justify-between w-64 mb-5 dark:text-gray-300'>
                  <label className='flex items-center text-xs py-2 '>
                    <input type='checkbox' name='remember' className='mr-1'/>Remember me
                  </label>
                  <a href='#' className='text-xs py-2'>Forgot Password</a>
                </div>
                
                <a href='#' onClick={handleClick} className='border-2 text-gray-700 dark:text-gray-400 border-gray-500  dark:border-gray-500 rounded-full px-12 py-2 inline-block font-semibold hover:bg-gray-400 dark:hover:bg-black hover:text-red-500 dark:hover:text-gray-300  transition duration-300'>
                  Sign in
                </a>
              </div>
            </div>
          </div>{/* sign in section */}
          <div className='w-2/5 bg-gray-200 dark:bg-[#1F1B24] text-gray-800 dark:text-gray-200 rounded-tr-2xl rounded-br-2xl py-36 px-12'>
            <h3 className='text-3xl font-bold text-gray-600 dark:text-gray-400'>Hello <span className='text-black  dark:text-gray-200'>{user?.username}</span></h3>
            <div className='border-2 w-10 border-orange-500 inline-block mb-2'></div>
            <p className='mb-2 text-gray-800 dark:text-[#a59eb5]'>Please fill up your personal information</p>
              <a  className='text-gray-800 dark:text-gray-600 border-2 border-gray-400  dark:border-gray-500 rounded-full px-12 py-2 inline-block font-semibold hover:bg-gray-200 dark:hover:bg-[#2c2739] hover:text-orange-500 dark:hover:text-gray-500 transition duration-300'>
                  <Link href='/register' className="underline">Sign up</Link>                
              </a>                 
          </div>{/* sign up section */}
        </div>
      </main>

    </div>
  )
}

export default Login;